on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: intl
      - name: Install dependencies
        run: |
          composer install
      - name: Tests
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
        run: php artisan test
      - name: Lint
        run: ./vendor/bin/pint --test
